# TOKYONIGHT THEME
# (You can save this as ~/.config/kitty/tokyonight.conf and then include it,
# or paste the colors directly here.)

include tokyo-night-kitty.conf


# FONT
font_family               Liga SFMono Nerd Font

# BACKGROUND OPACITY
background_opacity        0.85

# MAXIMIZE ON START (kitty has no direct option)
# Uncomment and tweak if you want to simulate a large window:
#initial_window_width  100%
#initial_window_height 100%

hide_window_decorations yes
