# improve colors
set -g default-terminal 'screen-256color'


# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

set -sg escape-time 0

# change leader key
set -g prefix2 C-s

# reload config
unbind j
bind r source-file ~/.config/tmux/tmux.conf


# unbind alt-f
unbind -n M-f
unbind M-f


# set vim binding
setw -g mode-keys vi
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R


bind-key -r C-h select-window -t :-
bind-key -r C-l select-window -t :+

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'toddyamakawa/tmux-prefixless'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-logging'

set -g @plugin 'fabioluciano/tmux-tokyo-night'

### Tokyo Night Theme configuration
set -g @theme_variation 'night'
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_plugins 'battery,yay,weather,datetime'

set -g @theme_plugin_weather_location 'Handewitt, Germany'
set -g @theme_plugin_battery_yellow_threshold 75
set -g @theme_plugin_battery_red_threshold 55

set -g @theme_plugin_datetime_format '%Y-%m-%d %H-%M'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
